name: Build/release

on:
  push:


jobs:
  release-linux:
    # the type of machine to run the job on
    runs-on: ${{ matrix.os }}
    
    # create a build matrix for jobs
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: âš™ï¸ Check out Git repository
        uses: actions/checkout@v4

      - name: âš™ï¸ Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: âš™ï¸ Install packages for building .flatpak
        if: matrix.os == 'ubuntu-latest'
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: flatpak flatpak-builder

      - name: âš™ï¸ yarn install
        run: yarn install
      - name: âš™ï¸ yarn run release
        run: yarn run release
      
      - name: ğŸŒï¸ Upload results
        uses: actions/upload-artifact@v4
        with:
          name: build1
          path: |
            dist/*.AppImage
            dist/*.pacman
            dist/*.deb
            dist/*.snap
            dist/*.rpm
            dist/*.flatpak
            dist/*.exe
      - name: ğŸš€ï¸ release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: "dist/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}