name: Build/release

on:
  push:


jobs:
  BuildOrRelease:
    # the type of machine to run the job on
    runs-on: ${{ matrix.os }}
    
    # create a build matrix for jobs
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: âš™ï¸ Check out Git repository
        uses: actions/checkout@v4

      - name: âš™ï¸ Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: âš™ï¸ğŸ“¦ï¸ Install flatpak for building .flatpak
        # https://www.electron.build/configuration/flatpak
        if: matrix.os == 'ubuntu-latest'
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: flatpak flatpak-builder
        
      - name: âš™ï¸ğŸ“¦ï¸ Install runtime,base for building .flatpak
        run: |
          flatpak install runtime/org.freedesktop.Platform/x86_64/23.08 -y
          flatpak install app/org.electronjs.Electron2.BaseApp/x86_64/23.08 -y
      
      - name: âš™ï¸ yarn install
        run: yarn install
      - name: âš™ï¸ yarn run release
        run: DEBUG="@malept/flatpak-bundler" yarn run release
      
      - name: ğŸŒï¸ Upload results
        uses: actions/upload-artifact@v4
        with:
          path: |
            dist/*.AppImage
            dist/*.pacman
            dist/*.deb
            dist/*.snap
            dist/*.rpm
            dist/*.flatpak
            dist/*.exe
      
      - name: ğŸš€ï¸ release
        uses: softprops/action-gh-release@v2
        with:
          files: "dist/*"
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
